# Generated by Django 3.1.2 on 2020-11-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='finished',
        ),
    ]
